/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    projects: Project;
    insights: Insight;
    'business-categories': BusinessCategory;
    companies: Company;
    brands: Brand;
    solutions: Solution;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    insights: InsightsSelect<false> | InsightsSelect<true>;
    'business-categories': BusinessCategoriesSelect<false> | BusinessCategoriesSelect<true>;
    companies: CompaniesSelect<false> | CompaniesSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    solutions: SolutionsSelect<false> | SolutionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    navigation: Navigation;
    footer: Footer;
    'site-settings': SiteSetting;
    about: About;
    'what-we-do': WhatWeDo;
    'creators-page': CreatorsPage;
    'contact-page': ContactPage;
    'home-page': HomePage;
  };
  globalsSelect: {
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    'what-we-do': WhatWeDoSelect<false> | WhatWeDoSelect<true>;
    'creators-page': CreatorsPageSelect<false> | CreatorsPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Owner = full control · Admin = content+users (not owner) · Editor = content/media · Viewer = read-only
   */
  role: 'owner' | 'admin' | 'editor' | 'viewer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Public CMS-managed media. (Existing /public/assets are unaffected.)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for accessibility & SEO. Required.
   */
  altText: string;
  caption?: string | null;
  /**
   * Photographer / source / attribution.
   */
  credit?: string | null;
  /**
   * Usage rights. 'HOLD' = not cleared for public use.
   */
  rightsStatus: 'geek-owned' | 'client-archive' | 'licensed' | 'press-reference' | 'unknown' | 'hold';
  /**
   * Licence terms, expiry, restrictions, approval source.
   */
  rightsNotes?: string | null;
  /**
   * e.g. 'No public event photography of identifiable guests.'
   */
  usageRestrictions?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    content?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * What Geek does. Doubles as a /services/[slug] SEO page — publish only when it has real content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * Display name, e.g. “Influencer Marketing”.
   */
  label: string;
  /**
   * Stable URL/filter value, e.g. “influencer-marketing”. Matches lib/work/taxonomy.ts. Do not change after launch.
   */
  slug: string;
  /**
   * Lower sorts first.
   */
  order?: number | null;
  hero?: {
    /**
     * Service page headline (falls back to the label).
     */
    heading?: string | null;
    shortSummary?: string | null;
  };
  introduction?: string | null;
  /**
   * Optional structured capabilities.
   */
  capabilities?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional — how Geek approaches this service.
   */
  approach?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    noindex?: boolean | null;
  };
  /**
   * Genuinely useful reader questions with concise, evidence-backed answers. Not keyword spam.
   */
  faqs?:
    | {
        question: string;
        /**
         * Concise, accurate answer shown to readers.
         */
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Editorial guidance for SEO/AEO research. These fields do NOT directly output a meta-keywords tag and are not publicly rendered unless explicitly mapped elsewhere.
   */
  searchStrategy?: {
    /**
     * Single primary target phrase, e.g. “MyLaysRelationchip campaign”.
     */
    primaryKeyword?: string | null;
    /**
     * Supporting keyword phrases (press Enter between them).
     */
    secondaryKeywords?: string[] | null;
    /**
     * Dominant intent for this entity/page.
     */
    searchIntent?: ('informational' | 'commercial' | 'branded' | 'transactional' | 'mixed') | null;
    /**
     * e.g. “India”. Free text — not a normalized geography collection.
     */
    targetMarket?: string | null;
    /**
     * When this research was captured.
     */
    keywordResearchDate?: string | null;
    /**
     * Real search/AEO questions found during research. Can seed the FAQ editor.
     */
    relatedQuestions?: string[] | null;
    /**
     * Editorial internal-linking hints only. NOT auto-injected as exact-match anchors.
     */
    preferredInternalAnchors?: string[] | null;
    /**
     * Internal strategy notes (SERP patterns, competitors, ambiguity, cannibalization, insight source). Never rendered publicly.
     */
    searchNotes?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Case studies. Drafts stay private; publish to go live. Existing /public/assets paths keep working.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  /**
   * Project name shown as the case-study title.
   */
  title: string;
  /**
   * URL segment: /work/<slug>. Lowercase, hyphenated.
   */
  slug: string;
  /**
   * Brand / client name.
   */
  client?: string | null;
  year?: number | null;
  location?: string | null;
  /**
   * One-line summary used at the top of the case study.
   */
  shortSummary?: string | null;
  /**
   * Shorter line for the /work card (falls back to shortSummary).
   */
  cardSummary?: string | null;
  /**
   * How this project renders. Flagship = bespoke developer renderer.
   */
  renderMode: 'standard' | 'flexible' | 'flagship';
  /**
   * Which developer-built renderer to use (flagship only).
   */
  flagshipRendererKey?: ('high-ultra-lounge' | 'the-coolest-job') | null;
  /**
   * Hero/card image (CMS). Or use heroLegacySrc.
   */
  heroMedia?: (number | null) | Media;
  /**
   * OR existing /public/assets hero path.
   */
  heroLegacySrc?: string | null;
  /**
   * Optional hero video path/URL.
   */
  heroVideo?: string | null;
  /**
   * What the work IS (separate from Render Mode, which is how it's PRESENTED). Programs vs campaigns group differently on the Brand hub.
   */
  projectKind?: ('campaign' | 'ongoing-program' | 'platform' | 'activation') | null;
  /**
   * Show in Featured Stories.
   */
  featured?: boolean | null;
  /**
   * Lower sorts first in the grid.
   */
  order?: number | null;
  /**
   * What Geek did (reusable Services taxonomy). Also powers the /work Service filter.
   */
  services?: (number | Service)[] | null;
  campaignTypes?:
    | (
        | 'brand-launch'
        | 'product-launch'
        | 'store-venue-launch'
        | 'integrated-campaign'
        | 'mass-creator-campaign'
        | 'influencer-campaign'
        | 'celebrity-campaign'
        | 'micro-influencer-campaign'
        | 'barter-campaign'
        | 'ugc-campaign'
        | 'social-campaign'
        | 'digital-campaign'
        | 'interactive-experience'
        | 'event-activation'
        | 'cause-campaign'
        | 'employer-branding'
        | 'content-campaign'
        | 'community-campaign'
        | 'referral-campaign'
        | 'recruitment-campaign'
        | 'long-term-partnership'
        | 'brand-building'
      )[]
    | null;
  /**
   * Industries (relationship). Preferred source of truth; the legacy select below is kept for back-compat.
   */
  businessCategories?: (number | BusinessCategory)[] | null;
  /**
   * Client company. Optional — corporate-level projects may set only this.
   */
  company?: (number | null) | Company;
  /**
   * Brand. Optional. If set, its company must match Company (auto-filled when Company is empty).
   */
  brand?: (number | null) | Brand;
  /**
   * Geek Solution(s) / IP this project implements (optional, e.g. IRM).
   */
  solutions?: (number | Solution)[] | null;
  /**
   * LEGACY industry select — kept for back-compat; prefer the Industries relationship above. Not removed.
   */
  businessCategory?:
    | (
        | 'fmcg'
        | 'food-beverage'
        | 'hospitality'
        | 'it-technology'
        | 'retail'
        | 'fashion'
        | 'beauty-personal-care'
        | 'automobile'
        | 'education'
        | 'real-estate'
        | 'financial-services'
        | 'aviation'
        | 'd2c'
        | 'lifestyle'
        | 'healthcare'
        | 'sustainability'
        | 'social-impact'
        | 'b2b'
      )[]
    | null;
  /**
   * Big case-study headline (falls back to title).
   */
  headline?: string | null;
  challenge?: {
    question?: string | null;
    copy?: string | null;
  };
  insight?: string | null;
  idea?: {
    statement?: string | null;
    copy?: string | null;
  };
  /**
   * Execution narrative (plain). Rich modular layouts belong in the Sections tab.
   */
  execution?: string | null;
  /**
   * Why it mattered / result (no invented metrics).
   */
  outcome?: string | null;
  quote?: {
    text?: string | null;
    attribution?: string | null;
  };
  metrics?:
    | {
        /**
         * e.g. 27.5M+
         */
        value: string;
        label: string;
        prefix?: string | null;
        suffix?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Content sections. React decides the exact styling.
   */
  sections?:
    | (
        | {
            eyebrow?: string | null;
            heading: string;
            body?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'sectionIntro';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            /**
             * CMS media (Vercel Blob). Leave empty to use a legacy path instead.
             */
            media?: (number | null) | Media;
            /**
             * OR an existing /public/assets/… path (for legacy assets not yet in the CMS).
             */
            legacySrc?: string | null;
            /**
             * Accessibility description (falls back to the media record's alt).
             */
            alt?: string | null;
            caption?: string | null;
            credit?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaBlock';
          }
        | {
            /**
             * CMS media (Vercel Blob). Leave empty to use a legacy path instead.
             */
            media?: (number | null) | Media;
            /**
             * OR an existing /public/assets/… path (for legacy assets not yet in the CMS).
             */
            legacySrc?: string | null;
            /**
             * Accessibility description (falls back to the media record's alt).
             */
            alt?: string | null;
            caption?: string | null;
            credit?: string | null;
            /**
             * Optional headline laid over the visual.
             */
            overlayHeading?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'fullBleedMedia';
          }
        | {
            mediaSide?: ('left' | 'right') | null;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            /**
             * CMS media (Vercel Blob). Leave empty to use a legacy path instead.
             */
            media?: (number | null) | Media;
            /**
             * OR an existing /public/assets/… path (for legacy assets not yet in the CMS).
             */
            legacySrc?: string | null;
            /**
             * Accessibility description (falls back to the media record's alt).
             */
            alt?: string | null;
            caption?: string | null;
            credit?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'splitContent';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  /**
                   * CMS media (Vercel Blob). Leave empty to use a legacy path instead.
                   */
                  media?: (number | null) | Media;
                  /**
                   * OR an existing /public/assets/… path (for legacy assets not yet in the CMS).
                   */
                  legacySrc?: string | null;
                  /**
                   * Accessibility description (falls back to the media record's alt).
                   */
                  alt?: string | null;
                  caption?: string | null;
                  credit?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaGallery';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  /**
                   * e.g. 2,229 · 103M+ · 27.5M+
                   */
                  value: string;
                  label: string;
                  prefix?: string | null;
                  suffix?: string | null;
                  note?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'metrics';
          }
        | {
            quote: string;
            attribution?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote';
          }
        | {
            heading: string;
            body?: string | null;
            buttonLabel?: string | null;
            buttonHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
      )[]
    | null;
  seo?: {
    /**
     * Falls back to “<title> — <client> | Geek”.
     */
    metaTitle?: string | null;
    /**
     * Falls back to the short summary.
     */
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * Exclude from indexing (rarely needed).
     */
    noindex?: boolean | null;
  };
  /**
   * External coverage. Distinguish coverage that mentions Geek from coverage that only validates the campaign.
   */
  pressCoverage?:
    | {
        /**
         * e.g. “ET BrandEquity”.
         */
        publisher: string;
        publicationDate?: string | null;
        /**
         * Original article title.
         */
        headline: string;
        /**
         * Validated external URL.
         */
        url: string;
        /**
         * Optional archive link (e.g. Wayback), for when the original may disappear.
         */
        archiveUrl?: string | null;
        sourceType:
          | 'independent-editorial'
          | 'official-brand'
          | 'partner-ngo'
          | 'campaign-archive'
          | 'trade-publication'
          | 'other';
        /**
         * Geek is explicitly named/featured (NOT merely campaign coverage).
         */
        geekMentioned?: boolean | null;
        /**
         * Surface prominently (keep to 3–4 strongest).
         */
        featured?: boolean | null;
        /**
         * What this source substantiates, e.g. “Validates launch, 3,000+ micro-influencer scale and AR-filter activation.”
         */
        validationNote?: string | null;
        /**
         * Optional — ONLY a Media asset intentionally imported with acceptable rights. Never hotlink a publication's image.
         */
        thumbnail?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Industry recognition. Be precise about who was credited — an award for the campaign may credit the client/partners, not Geek.
   */
  awards?:
    | {
        /**
         * e.g. “MarCom Awards”.
         */
        awardBody: string;
        /**
         * e.g. “MarCom Awards 2021”.
         */
        programName?: string | null;
        /**
         * e.g. “Integrated Marketing”. Optional.
         */
        category?: string | null;
        /**
         * e.g. “Gold”.
         */
        result?: string | null;
        year?: number | null;
        /**
         * External source / archive.
         */
        url?: string | null;
        /**
         * Organisations credited by this award (e.g. PepsiCo, Wunderman Thompson). May not include Geek.
         */
        creditedOrganizations?: string[] | null;
        /**
         * Geek is explicitly credited by this award.
         */
        geekCredited?: boolean | null;
        /**
         * What this award validates.
         */
        validationNote?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Genuinely useful reader questions with concise, evidence-backed answers. Not keyword spam.
   */
  faqs?:
    | {
        question: string;
        /**
         * Concise, accurate answer shown to readers.
         */
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Editorial guidance for SEO/AEO research. These fields do NOT directly output a meta-keywords tag and are not publicly rendered unless explicitly mapped elsewhere.
   */
  searchStrategy?: {
    /**
     * Single primary target phrase, e.g. “MyLaysRelationchip campaign”.
     */
    primaryKeyword?: string | null;
    /**
     * Supporting keyword phrases (press Enter between them).
     */
    secondaryKeywords?: string[] | null;
    /**
     * Dominant intent for this entity/page.
     */
    searchIntent?: ('informational' | 'commercial' | 'branded' | 'transactional' | 'mixed') | null;
    /**
     * e.g. “India”. Free text — not a normalized geography collection.
     */
    targetMarket?: string | null;
    /**
     * When this research was captured.
     */
    keywordResearchDate?: string | null;
    /**
     * Real search/AEO questions found during research. Can seed the FAQ editor.
     */
    relatedQuestions?: string[] | null;
    /**
     * Editorial internal-linking hints only. NOT auto-injected as exact-match anchors.
     */
    preferredInternalAnchors?: string[] | null;
    /**
     * Internal strategy notes (SERP patterns, competitors, ambiguity, cannibalization, insight source). Never rendered publicly.
     */
    searchNotes?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Industry/vertical hub pages at /industries/[slug]. Publish only when useful content exists.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-categories".
 */
export interface BusinessCategory {
  id: number;
  /**
   * e.g. “FMCG”.
   */
  name: string;
  /**
   * URL: /industries/<slug>. Auto-filled from name on create.
   */
  slug?: string | null;
  /**
   * One-line positioning used on cards and hero.
   */
  shortSummary?: string | null;
  /**
   * Editorial positioning of Geek's work in this industry.
   */
  introduction?: string | null;
  heroMedia?: (number | null) | Media;
  /**
   * OR an existing /public/assets path.
   */
  heroLegacySrc?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    noindex?: boolean | null;
  };
  /**
   * Genuinely useful reader questions with concise, evidence-backed answers. Not keyword spam.
   */
  faqs?:
    | {
        question: string;
        /**
         * Concise, accurate answer shown to readers.
         */
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Editorial guidance for SEO/AEO research. These fields do NOT directly output a meta-keywords tag and are not publicly rendered unless explicitly mapped elsewhere.
   */
  searchStrategy?: {
    /**
     * Single primary target phrase, e.g. “MyLaysRelationchip campaign”.
     */
    primaryKeyword?: string | null;
    /**
     * Supporting keyword phrases (press Enter between them).
     */
    secondaryKeywords?: string[] | null;
    /**
     * Dominant intent for this entity/page.
     */
    searchIntent?: ('informational' | 'commercial' | 'branded' | 'transactional' | 'mixed') | null;
    /**
     * e.g. “India”. Free text — not a normalized geography collection.
     */
    targetMarket?: string | null;
    /**
     * When this research was captured.
     */
    keywordResearchDate?: string | null;
    /**
     * Real search/AEO questions found during research. Can seed the FAQ editor.
     */
    relatedQuestions?: string[] | null;
    /**
     * Editorial internal-linking hints only. NOT auto-injected as exact-match anchors.
     */
    preferredInternalAnchors?: string[] | null;
    /**
     * Internal strategy notes (SERP patterns, competitors, ambiguity, cannibalization, insight source). Never rendered publicly.
     */
    searchNotes?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Company hub pages at /companies/[slug]. Publish only when useful content exists.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies".
 */
export interface Company {
  id: number;
  /**
   * e.g. “PepsiCo”.
   */
  name: string;
  /**
   * URL: /companies/<slug>. Auto-filled from name on create.
   */
  slug?: string | null;
  logo?: (number | null) | Media;
  /**
   * OR an existing /public/assets logo path.
   */
  legacyLogoSrc?: string | null;
  /**
   * Optional external website.
   */
  website?: string | null;
  shortSummary?: string | null;
  /**
   * The Geek–company relationship, in brief.
   */
  introduction?: string | null;
  /**
   * Industries this company operates in.
   */
  businessCategories?: (number | BusinessCategory)[] | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    noindex?: boolean | null;
  };
  /**
   * External coverage. Distinguish coverage that mentions Geek from coverage that only validates the campaign.
   */
  pressCoverage?:
    | {
        /**
         * e.g. “ET BrandEquity”.
         */
        publisher: string;
        publicationDate?: string | null;
        /**
         * Original article title.
         */
        headline: string;
        /**
         * Validated external URL.
         */
        url: string;
        /**
         * Optional archive link (e.g. Wayback), for when the original may disappear.
         */
        archiveUrl?: string | null;
        sourceType:
          | 'independent-editorial'
          | 'official-brand'
          | 'partner-ngo'
          | 'campaign-archive'
          | 'trade-publication'
          | 'other';
        /**
         * Geek is explicitly named/featured (NOT merely campaign coverage).
         */
        geekMentioned?: boolean | null;
        /**
         * Surface prominently (keep to 3–4 strongest).
         */
        featured?: boolean | null;
        /**
         * What this source substantiates, e.g. “Validates launch, 3,000+ micro-influencer scale and AR-filter activation.”
         */
        validationNote?: string | null;
        /**
         * Optional — ONLY a Media asset intentionally imported with acceptable rights. Never hotlink a publication's image.
         */
        thumbnail?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Industry recognition. Be precise about who was credited — an award for the campaign may credit the client/partners, not Geek.
   */
  awards?:
    | {
        /**
         * e.g. “MarCom Awards”.
         */
        awardBody: string;
        /**
         * e.g. “MarCom Awards 2021”.
         */
        programName?: string | null;
        /**
         * e.g. “Integrated Marketing”. Optional.
         */
        category?: string | null;
        /**
         * e.g. “Gold”.
         */
        result?: string | null;
        year?: number | null;
        /**
         * External source / archive.
         */
        url?: string | null;
        /**
         * Organisations credited by this award (e.g. PepsiCo, Wunderman Thompson). May not include Geek.
         */
        creditedOrganizations?: string[] | null;
        /**
         * Geek is explicitly credited by this award.
         */
        geekCredited?: boolean | null;
        /**
         * What this award validates.
         */
        validationNote?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Genuinely useful reader questions with concise, evidence-backed answers. Not keyword spam.
   */
  faqs?:
    | {
        question: string;
        /**
         * Concise, accurate answer shown to readers.
         */
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Editorial guidance for SEO/AEO research. These fields do NOT directly output a meta-keywords tag and are not publicly rendered unless explicitly mapped elsewhere.
   */
  searchStrategy?: {
    /**
     * Single primary target phrase, e.g. “MyLaysRelationchip campaign”.
     */
    primaryKeyword?: string | null;
    /**
     * Supporting keyword phrases (press Enter between them).
     */
    secondaryKeywords?: string[] | null;
    /**
     * Dominant intent for this entity/page.
     */
    searchIntent?: ('informational' | 'commercial' | 'branded' | 'transactional' | 'mixed') | null;
    /**
     * e.g. “India”. Free text — not a normalized geography collection.
     */
    targetMarket?: string | null;
    /**
     * When this research was captured.
     */
    keywordResearchDate?: string | null;
    /**
     * Real search/AEO questions found during research. Can seed the FAQ editor.
     */
    relatedQuestions?: string[] | null;
    /**
     * Editorial internal-linking hints only. NOT auto-injected as exact-match anchors.
     */
    preferredInternalAnchors?: string[] | null;
    /**
     * Internal strategy notes (SERP patterns, competitors, ambiguity, cannibalization, insight source). Never rendered publicly.
     */
    searchNotes?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Brand hub pages at /brands/[slug]. Publish only when useful content exists.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  /**
   * e.g. “Lay's”.
   */
  name: string;
  /**
   * URL: /brands/<slug>. Auto-filled from name on create.
   */
  slug?: string | null;
  /**
   * Parent company (e.g. PepsiCo).
   */
  company?: (number | null) | Company;
  /**
   * Simple grouping on the Company hub, e.g. “Foods” or “Beverages”.
   */
  portfolioGroup?: string | null;
  logo?: (number | null) | Media;
  /**
   * OR an existing /public/assets logo path.
   */
  legacyLogoSrc?: string | null;
  shortSummary?: string | null;
  introduction?: string | null;
  heroMedia?: (number | null) | Media;
  /**
   * OR an existing /public/assets path.
   */
  heroLegacySrc?: string | null;
  /**
   * Industries this brand belongs to (usually inherited from its company, but set explicitly here).
   */
  businessCategories?: (number | BusinessCategory)[] | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    noindex?: boolean | null;
  };
  /**
   * External coverage. Distinguish coverage that mentions Geek from coverage that only validates the campaign.
   */
  pressCoverage?:
    | {
        /**
         * e.g. “ET BrandEquity”.
         */
        publisher: string;
        publicationDate?: string | null;
        /**
         * Original article title.
         */
        headline: string;
        /**
         * Validated external URL.
         */
        url: string;
        /**
         * Optional archive link (e.g. Wayback), for when the original may disappear.
         */
        archiveUrl?: string | null;
        sourceType:
          | 'independent-editorial'
          | 'official-brand'
          | 'partner-ngo'
          | 'campaign-archive'
          | 'trade-publication'
          | 'other';
        /**
         * Geek is explicitly named/featured (NOT merely campaign coverage).
         */
        geekMentioned?: boolean | null;
        /**
         * Surface prominently (keep to 3–4 strongest).
         */
        featured?: boolean | null;
        /**
         * What this source substantiates, e.g. “Validates launch, 3,000+ micro-influencer scale and AR-filter activation.”
         */
        validationNote?: string | null;
        /**
         * Optional — ONLY a Media asset intentionally imported with acceptable rights. Never hotlink a publication's image.
         */
        thumbnail?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Industry recognition. Be precise about who was credited — an award for the campaign may credit the client/partners, not Geek.
   */
  awards?:
    | {
        /**
         * e.g. “MarCom Awards”.
         */
        awardBody: string;
        /**
         * e.g. “MarCom Awards 2021”.
         */
        programName?: string | null;
        /**
         * e.g. “Integrated Marketing”. Optional.
         */
        category?: string | null;
        /**
         * e.g. “Gold”.
         */
        result?: string | null;
        year?: number | null;
        /**
         * External source / archive.
         */
        url?: string | null;
        /**
         * Organisations credited by this award (e.g. PepsiCo, Wunderman Thompson). May not include Geek.
         */
        creditedOrganizations?: string[] | null;
        /**
         * Geek is explicitly credited by this award.
         */
        geekCredited?: boolean | null;
        /**
         * What this award validates.
         */
        validationNote?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Genuinely useful reader questions with concise, evidence-backed answers. Not keyword spam.
   */
  faqs?:
    | {
        question: string;
        /**
         * Concise, accurate answer shown to readers.
         */
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Editorial guidance for SEO/AEO research. These fields do NOT directly output a meta-keywords tag and are not publicly rendered unless explicitly mapped elsewhere.
   */
  searchStrategy?: {
    /**
     * Single primary target phrase, e.g. “MyLaysRelationchip campaign”.
     */
    primaryKeyword?: string | null;
    /**
     * Supporting keyword phrases (press Enter between them).
     */
    secondaryKeywords?: string[] | null;
    /**
     * Dominant intent for this entity/page.
     */
    searchIntent?: ('informational' | 'commercial' | 'branded' | 'transactional' | 'mixed') | null;
    /**
     * e.g. “India”. Free text — not a normalized geography collection.
     */
    targetMarket?: string | null;
    /**
     * When this research was captured.
     */
    keywordResearchDate?: string | null;
    /**
     * Real search/AEO questions found during research. Can seed the FAQ editor.
     */
    relatedQuestions?: string[] | null;
    /**
     * Editorial internal-linking hints only. NOT auto-injected as exact-match anchors.
     */
    preferredInternalAnchors?: string[] | null;
    /**
     * Internal strategy notes (SERP patterns, competitors, ambiguity, cannibalization, insight source). Never rendered publicly.
     */
    searchNotes?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Geek solution / IP hub pages at /solutions/[slug]. Publish only when useful content exists.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions".
 */
export interface Solution {
  id: number;
  /**
   * e.g. “Influencer Relationship Management”.
   */
  name: string;
  /**
   * URL: /solutions/<slug>. Auto-filled from name on create.
   */
  slug?: string | null;
  /**
   * What kind of reusable asset this is.
   */
  solutionType?: ('proprietary-ip' | 'methodology' | 'program-model' | 'solution') | null;
  shortSummary?: string | null;
  introduction?: string | null;
  /**
   * Service(s) this solution is part of / related to (e.g. Influencer Marketing).
   */
  relatedServices?: (number | Service)[] | null;
  whatItSolves?: {
    heading?: string | null;
    body?: string | null;
  };
  /**
   * Optional structured methodology steps.
   */
  methodology?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    noindex?: boolean | null;
  };
  /**
   * External coverage. Distinguish coverage that mentions Geek from coverage that only validates the campaign.
   */
  pressCoverage?:
    | {
        /**
         * e.g. “ET BrandEquity”.
         */
        publisher: string;
        publicationDate?: string | null;
        /**
         * Original article title.
         */
        headline: string;
        /**
         * Validated external URL.
         */
        url: string;
        /**
         * Optional archive link (e.g. Wayback), for when the original may disappear.
         */
        archiveUrl?: string | null;
        sourceType:
          | 'independent-editorial'
          | 'official-brand'
          | 'partner-ngo'
          | 'campaign-archive'
          | 'trade-publication'
          | 'other';
        /**
         * Geek is explicitly named/featured (NOT merely campaign coverage).
         */
        geekMentioned?: boolean | null;
        /**
         * Surface prominently (keep to 3–4 strongest).
         */
        featured?: boolean | null;
        /**
         * What this source substantiates, e.g. “Validates launch, 3,000+ micro-influencer scale and AR-filter activation.”
         */
        validationNote?: string | null;
        /**
         * Optional — ONLY a Media asset intentionally imported with acceptable rights. Never hotlink a publication's image.
         */
        thumbnail?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Genuinely useful reader questions with concise, evidence-backed answers. Not keyword spam.
   */
  faqs?:
    | {
        question: string;
        /**
         * Concise, accurate answer shown to readers.
         */
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Editorial guidance for SEO/AEO research. These fields do NOT directly output a meta-keywords tag and are not publicly rendered unless explicitly mapped elsewhere.
   */
  searchStrategy?: {
    /**
     * Single primary target phrase, e.g. “MyLaysRelationchip campaign”.
     */
    primaryKeyword?: string | null;
    /**
     * Supporting keyword phrases (press Enter between them).
     */
    secondaryKeywords?: string[] | null;
    /**
     * Dominant intent for this entity/page.
     */
    searchIntent?: ('informational' | 'commercial' | 'branded' | 'transactional' | 'mixed') | null;
    /**
     * e.g. “India”. Free text — not a normalized geography collection.
     */
    targetMarket?: string | null;
    /**
     * When this research was captured.
     */
    keywordResearchDate?: string | null;
    /**
     * Real search/AEO questions found during research. Can seed the FAQ editor.
     */
    relatedQuestions?: string[] | null;
    /**
     * Editorial internal-linking hints only. NOT auto-injected as exact-match anchors.
     */
    preferredInternalAnchors?: string[] | null;
    /**
     * Internal strategy notes (SERP patterns, competitors, ambiguity, cannibalization, insight source). Never rendered publicly.
     */
    searchNotes?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Editorial articles for /insights. Save a draft and use Preview before publishing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights".
 */
export interface Insight {
  id: number;
  /**
   * Article title (shown as the headline and card title).
   */
  title: string;
  /**
   * URL segment: /insights/<slug>. Auto-filled from the title on create; keep it stable after publishing to preserve backlinks.
   */
  slug?: string | null;
  /**
   * Standfirst / dek — the summary shown under the title and on the card.
   */
  excerpt?: string | null;
  /**
   * Original publication date. Drives ordering, SEO and the sitemap.
   */
  publishDate?: string | null;
  /**
   * Hero / card image (CMS upload). Or use the legacy path.
   */
  heroMedia?: (number | null) | Media;
  /**
   * OR an existing /public/assets image path.
   */
  heroLegacySrc?: string | null;
  /**
   * Article body — headings, paragraphs, lists, links, quotes.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Editorial category (drives the /insights filter).
   */
  category:
    'geek-decoded' | 'creator-economy' | 'brand-building' | 'social-culture' | 'whats-next' | 'case-study-learnings';
  seo?: {
    /**
     * Falls back to “<title> | Geek Insights”.
     */
    metaTitle?: string | null;
    /**
     * Falls back to the excerpt.
     */
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'insights';
        value: number | Insight;
      } | null)
    | ({
        relationTo: 'business-categories';
        value: number | BusinessCategory;
      } | null)
    | ({
        relationTo: 'companies';
        value: number | Company;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'solutions';
        value: number | Solution;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  altText?: T;
  caption?: T;
  credit?: T;
  rightsStatus?: T;
  rightsNotes?: T;
  usageRestrictions?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        content?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  label?: T;
  slug?: T;
  order?: T;
  hero?:
    | T
    | {
        heading?: T;
        shortSummary?: T;
      };
  introduction?: T;
  capabilities?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  approach?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noindex?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  searchStrategy?:
    | T
    | {
        primaryKeyword?: T;
        secondaryKeywords?: T;
        searchIntent?: T;
        targetMarket?: T;
        keywordResearchDate?: T;
        relatedQuestions?: T;
        preferredInternalAnchors?: T;
        searchNotes?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  client?: T;
  year?: T;
  location?: T;
  shortSummary?: T;
  cardSummary?: T;
  renderMode?: T;
  flagshipRendererKey?: T;
  heroMedia?: T;
  heroLegacySrc?: T;
  heroVideo?: T;
  projectKind?: T;
  featured?: T;
  order?: T;
  services?: T;
  campaignTypes?: T;
  businessCategories?: T;
  company?: T;
  brand?: T;
  solutions?: T;
  businessCategory?: T;
  headline?: T;
  challenge?:
    | T
    | {
        question?: T;
        copy?: T;
      };
  insight?: T;
  idea?:
    | T
    | {
        statement?: T;
        copy?: T;
      };
  execution?: T;
  outcome?: T;
  quote?:
    | T
    | {
        text?: T;
        attribution?: T;
      };
  metrics?:
    | T
    | {
        value?: T;
        label?: T;
        prefix?: T;
        suffix?: T;
        note?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        sectionIntro?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        mediaBlock?:
          | T
          | {
              media?: T;
              legacySrc?: T;
              alt?: T;
              caption?: T;
              credit?: T;
              id?: T;
              blockName?: T;
            };
        fullBleedMedia?:
          | T
          | {
              media?: T;
              legacySrc?: T;
              alt?: T;
              caption?: T;
              credit?: T;
              overlayHeading?: T;
              id?: T;
              blockName?: T;
            };
        splitContent?:
          | T
          | {
              mediaSide?: T;
              content?: T;
              media?: T;
              legacySrc?: T;
              alt?: T;
              caption?: T;
              credit?: T;
              id?: T;
              blockName?: T;
            };
        mediaGallery?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    media?: T;
                    legacySrc?: T;
                    alt?: T;
                    caption?: T;
                    credit?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        metrics?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    prefix?: T;
                    suffix?: T;
                    note?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              quote?: T;
              attribution?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              body?: T;
              buttonLabel?: T;
              buttonHref?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noindex?: T;
      };
  pressCoverage?:
    | T
    | {
        publisher?: T;
        publicationDate?: T;
        headline?: T;
        url?: T;
        archiveUrl?: T;
        sourceType?: T;
        geekMentioned?: T;
        featured?: T;
        validationNote?: T;
        thumbnail?: T;
        id?: T;
      };
  awards?:
    | T
    | {
        awardBody?: T;
        programName?: T;
        category?: T;
        result?: T;
        year?: T;
        url?: T;
        creditedOrganizations?: T;
        geekCredited?: T;
        validationNote?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  searchStrategy?:
    | T
    | {
        primaryKeyword?: T;
        secondaryKeywords?: T;
        searchIntent?: T;
        targetMarket?: T;
        keywordResearchDate?: T;
        relatedQuestions?: T;
        preferredInternalAnchors?: T;
        searchNotes?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights_select".
 */
export interface InsightsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  publishDate?: T;
  heroMedia?: T;
  heroLegacySrc?: T;
  body?: T;
  category?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-categories_select".
 */
export interface BusinessCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  shortSummary?: T;
  introduction?: T;
  heroMedia?: T;
  heroLegacySrc?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noindex?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  searchStrategy?:
    | T
    | {
        primaryKeyword?: T;
        secondaryKeywords?: T;
        searchIntent?: T;
        targetMarket?: T;
        keywordResearchDate?: T;
        relatedQuestions?: T;
        preferredInternalAnchors?: T;
        searchNotes?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies_select".
 */
export interface CompaniesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  legacyLogoSrc?: T;
  website?: T;
  shortSummary?: T;
  introduction?: T;
  businessCategories?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noindex?: T;
      };
  pressCoverage?:
    | T
    | {
        publisher?: T;
        publicationDate?: T;
        headline?: T;
        url?: T;
        archiveUrl?: T;
        sourceType?: T;
        geekMentioned?: T;
        featured?: T;
        validationNote?: T;
        thumbnail?: T;
        id?: T;
      };
  awards?:
    | T
    | {
        awardBody?: T;
        programName?: T;
        category?: T;
        result?: T;
        year?: T;
        url?: T;
        creditedOrganizations?: T;
        geekCredited?: T;
        validationNote?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  searchStrategy?:
    | T
    | {
        primaryKeyword?: T;
        secondaryKeywords?: T;
        searchIntent?: T;
        targetMarket?: T;
        keywordResearchDate?: T;
        relatedQuestions?: T;
        preferredInternalAnchors?: T;
        searchNotes?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  company?: T;
  portfolioGroup?: T;
  logo?: T;
  legacyLogoSrc?: T;
  shortSummary?: T;
  introduction?: T;
  heroMedia?: T;
  heroLegacySrc?: T;
  businessCategories?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noindex?: T;
      };
  pressCoverage?:
    | T
    | {
        publisher?: T;
        publicationDate?: T;
        headline?: T;
        url?: T;
        archiveUrl?: T;
        sourceType?: T;
        geekMentioned?: T;
        featured?: T;
        validationNote?: T;
        thumbnail?: T;
        id?: T;
      };
  awards?:
    | T
    | {
        awardBody?: T;
        programName?: T;
        category?: T;
        result?: T;
        year?: T;
        url?: T;
        creditedOrganizations?: T;
        geekCredited?: T;
        validationNote?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  searchStrategy?:
    | T
    | {
        primaryKeyword?: T;
        secondaryKeywords?: T;
        searchIntent?: T;
        targetMarket?: T;
        keywordResearchDate?: T;
        relatedQuestions?: T;
        preferredInternalAnchors?: T;
        searchNotes?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions_select".
 */
export interface SolutionsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  solutionType?: T;
  shortSummary?: T;
  introduction?: T;
  relatedServices?: T;
  whatItSolves?:
    | T
    | {
        heading?: T;
        body?: T;
      };
  methodology?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noindex?: T;
      };
  pressCoverage?:
    | T
    | {
        publisher?: T;
        publicationDate?: T;
        headline?: T;
        url?: T;
        archiveUrl?: T;
        sourceType?: T;
        geekMentioned?: T;
        featured?: T;
        validationNote?: T;
        thumbnail?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  searchStrategy?:
    | T
    | {
        primaryKeyword?: T;
        secondaryKeywords?: T;
        searchIntent?: T;
        targetMarket?: T;
        keywordResearchDate?: T;
        relatedQuestions?: T;
        preferredInternalAnchors?: T;
        searchNotes?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Header menu links, in order. Drag to reorder.
   */
  items?:
    | {
        label: string;
        /**
         * Internal path (e.g. /work) or a full external URL (https://…).
         */
        href: string;
        /**
         * Uncheck to hide without deleting.
         */
        enabled?: boolean | null;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The highlighted button on the right of the header.
   */
  cta?: {
    label?: string | null;
    /**
     * Where the button links (e.g. /creators).
     */
    href?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * The large cyan band above the footer. The highlighted word is hand-lettered by the design.
   */
  cta?: {
    /**
     * Text before the highlighted word.
     */
    headingPrefix?: string | null;
    /**
     * The hand-lettered word.
     */
    headingHighlight?: string | null;
    /**
     * Text after it.
     */
    headingSuffix?: string | null;
    buttonLabel?: string | null;
    /**
     * e.g. /contact
     */
    buttonHref?: string | null;
  };
  /**
   * Short line beside the logo in the footer strip.
   */
  tagline?: string | null;
  /**
   * Leave empty to show “© <current year> Geek Creative Agency”.
   */
  copyrightText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Full agency name.
   */
  name?: string | null;
  /**
   * Short name (e.g. Geek).
   */
  short?: string | null;
  /**
   * One–two sentence agency descriptor (also the default meta description).
   */
  description?: string | null;
  /**
   * The single source of social links — the footer and JSON-LD read these.
   */
  socialLinks?:
    | {
        platform: 'instagram' | 'linkedin' | 'youtube' | 'x' | 'facebook';
        /**
         * Display label (defaults to the platform name).
         */
        label?: string | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * Homepage / default browser title.
     */
    defaultTitle?: string | null;
    /**
     * Optional, e.g. “%s | Geek”. Leave empty — existing pages set complete titles.
     */
    titleTemplate?: string | null;
    defaultDescription?: string | null;
    /**
     * Default social share image.
     */
    defaultOgImage?: (number | null) | Media;
    /**
     * Organization name for structured data.
     */
    orgName?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The /about page. Save a draft and use Preview to review before publishing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  hero?: {
    /**
     * First line of the big heading (e.g. “Why”).
     */
    headingLine1?: string | null;
    /**
     * Second line — shown highlighted (e.g. “Geek”?).
     */
    headingLine2?: string | null;
    /**
     * The bold opening line under the heading.
     */
    lead?: string | null;
    paragraphs?:
      | {
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  evolution?: {
    /**
     * Small label above the era words (e.g. “Since 2008”).
     */
    eyebrow?: string | null;
    /**
     * The evolution words; the last one is shown highlighted.
     */
    eras?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Heading, main part.
     */
    headingMain?: string | null;
    /**
     * Heading, muted second part.
     */
    headingMuted?: string | null;
  };
  win?: {
    eyebrow?: string | null;
    /**
     * First line (e.g. “We win”).
     */
    headingLine1?: string | null;
    /**
     * Second line (e.g. “when you win.”).
     */
    headingLine2?: string | null;
    /**
     * The word in the second line to highlight (e.g. “you”).
     */
    highlight?: string | null;
    subcopy?: string | null;
  };
  geekWay?: {
    heading?: string | null;
    /**
     * The numbered list; the last item is shown highlighted.
     */
    principles?:
      | {
          title: string;
          body?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * Exclude this page from search indexing (rarely needed).
     */
    noindex?: boolean | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The /what-we-do page. Save a draft and use Preview before publishing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "what-we-do".
 */
export interface WhatWeDo {
  id: number;
  hero?: {
    /**
     * First heading block. Use line breaks for the intended wrapping.
     */
    block1?: string | null;
    /**
     * Second heading block (muted).
     */
    block2?: string | null;
    /**
     * Word in the second block shown highlighted (e.g. “problem.”).
     */
    highlight?: string | null;
    intro?: string | null;
  };
  /**
   * The Build / Create / Connect / Influence / Amplify bands.
   */
  capabilities?:
    | {
        /**
         * e.g. “Build.”
         */
        label: string;
        /**
         * The capability words listed under the label.
         */
        items?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        /**
         * The big statement. Use a line break for the two lines.
         */
        thought?: string | null;
        /**
         * Optional part of the statement to highlight cyan.
         */
        thoughtHighlight?: string | null;
        /**
         * Optional link under the statement.
         */
        linkLabel?: string | null;
        linkHref?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Page-specific button (separate from the global footer CTA).
   */
  cta?: {
    label?: string | null;
    href?: string | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    noindex?: boolean | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The /creators page. Save a draft and use Preview before publishing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "creators-page".
 */
export interface CreatorsPage {
  id: number;
  hero?: {
    /**
     * Main heading. Use a line break for the two lines.
     */
    headingBlock?: string | null;
    /**
     * Part of the heading shown highlighted (e.g. “With great brands.”).
     */
    headingHighlight?: string | null;
    subline?: string | null;
    ctaLabel?: string | null;
    /**
     * e.g. #join (scrolls to the form) or another route.
     */
    ctaHref?: string | null;
  };
  oneDegree?: {
    /**
     * Use a line break for the two lines.
     */
    heading?: string | null;
    body?: string | null;
    opportunities?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  whyGeek?: {
    eyebrow?: string | null;
    /**
     * Use line breaks for each line.
     */
    heading?: string | null;
    /**
     * Line to highlight (e.g. “Real opportunities.”).
     */
    headingHighlight?: string | null;
  };
  /**
   * Copy above the registration form (the form itself is fixed).
   */
  join?: {
    eyebrow?: string | null;
    heading?: string | null;
    subcopy?: string | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    noindex?: boolean | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The /contact page. Save a draft and use Preview before publishing. The forms themselves are fixed.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  hero?: {
    /**
     * The big heading. Use a line break for the two lines (e.g. “What should” / “we make matter next?”).
     */
    headingBlock?: string | null;
    /**
     * Word in the heading shown highlighted cyan (e.g. “matter”).
     */
    headingHighlight?: string | null;
    /**
     * Small label above the form (e.g. “Tell us the problem”).
     */
    formEyebrow?: string | null;
  };
  /**
   * The “What brings you to Geek?” section. You can relabel the four doors, but their forms and styling are fixed.
   */
  doors?: {
    /**
     * e.g. “Four doors.”
     */
    eyebrow?: string | null;
    /**
     * e.g. “What brings you to Geek?”
     */
    heading?: string | null;
    /**
     * One row per door. The Type selects which fixed door/form this labels; Title and Sub are the editable text.
     */
    items?:
      | {
          /**
           * Which fixed door this labels.
           */
          key: 'client' | 'creator' | 'career' | 'vendor';
          /**
           * e.g. “Build my brand.”
           */
          title: string;
          /**
           * e.g. “For Clients.”
           */
          sub: string;
          id?: string | null;
        }[]
      | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    noindex?: boolean | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The homepage ( / ). Editorial copy only — layout, motion and imagery are fixed. Save a draft and use Preview before publishing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero?: {
    /**
     * The big headline. Use line breaks for the three lines.
     */
    headingBlock?: string | null;
    /**
     * Word/phrase shown highlighted cyan (e.g. “matter.”).
     */
    headingHighlight?: string | null;
    subline?: string | null;
    ctaPrimaryLabel?: string | null;
    ctaPrimaryHref?: string | null;
    ctaSecondaryLabel?: string | null;
    ctaSecondaryHref?: string | null;
  };
  /**
   * The client logo marquee heading (the logos themselves are fixed).
   */
  logoWall?: {
    heading?: string | null;
    /**
     * Word highlighted cyan (e.g. “friends”).
     */
    headingHighlight?: string | null;
  };
  /**
   * “Build.” band (the work cards are fixed).
   */
  build?: {
    title?: string | null;
    sub?: string | null;
    trailing?: string | null;
  };
  /**
   * “Create.” band. Use a line break in the sub for the two lines.
   */
  create?: {
    title?: string | null;
    sub?: string | null;
  };
  /**
   * “Influence.” band (the creator mosaic is fixed).
   */
  influence?: {
    eyebrow?: string | null;
    heading?: string | null;
    sub?: string | null;
    /**
     * e.g. “Celebrity. Macro. Micro. Nano. UGC. Regional.”
     */
    list?: string | null;
    linkLabel?: string | null;
    linkHref?: string | null;
  };
  /**
   * “Proof.” band (the metrics are fixed).
   */
  proof?: {
    eyebrow?: string | null;
    sub?: string | null;
  };
  /**
   * The process rail (the steps + icons are fixed).
   */
  process?: {
    heading?: string | null;
    /**
     * Part of the heading highlighted cyan (e.g. “to the last mile.”).
     */
    headingHighlight?: string | null;
    /**
     * e.g. “We make it happen.”
     */
    trailing?: string | null;
  };
  /**
   * The dark “Built by Geek” section (the two stories are fixed).
   */
  builtByGeek?: {
    eyebrow?: string | null;
    /**
     * Main heading. Use a line break for the two lines.
     */
    headingBlock?: string | null;
    /**
     * The cyan line under the heading (e.g. “We write our own.”).
     */
    headingCyan?: string | null;
    /**
     * The closing statement.
     */
    closing?: string | null;
    /**
     * Word highlighted cyan (e.g. “exist.”).
     */
    closingHighlight?: string | null;
  };
  geekWay?: {
    title?: string | null;
    principles?:
      | {
          title: string;
          body?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * The big finale. Use a line break for the two lines (e.g. “We win” / “when you win.”).
     */
    finaleBlock?: string | null;
    /**
     * Word highlighted cyan (e.g. “you”).
     */
    finaleHighlight?: string | null;
    finaleSub?: string | null;
  };
  /**
   * “The Work.” band heading (the work wall items are fixed).
   */
  work?: {
    title?: string | null;
    sub?: string | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    noindex?: boolean | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        href?: T;
        enabled?: T;
        openInNewTab?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  cta?:
    | T
    | {
        headingPrefix?: T;
        headingHighlight?: T;
        headingSuffix?: T;
        buttonLabel?: T;
        buttonHref?: T;
      };
  tagline?: T;
  copyrightText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  short?: T;
  description?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        label?: T;
        url?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        defaultTitle?: T;
        titleTemplate?: T;
        defaultDescription?: T;
        defaultOgImage?: T;
        orgName?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headingLine1?: T;
        headingLine2?: T;
        lead?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  evolution?:
    | T
    | {
        eyebrow?: T;
        eras?:
          | T
          | {
              label?: T;
              id?: T;
            };
        headingMain?: T;
        headingMuted?: T;
      };
  win?:
    | T
    | {
        eyebrow?: T;
        headingLine1?: T;
        headingLine2?: T;
        highlight?: T;
        subcopy?: T;
      };
  geekWay?:
    | T
    | {
        heading?: T;
        principles?:
          | T
          | {
              title?: T;
              body?: T;
              id?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noindex?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "what-we-do_select".
 */
export interface WhatWeDoSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        block1?: T;
        block2?: T;
        highlight?: T;
        intro?: T;
      };
  capabilities?:
    | T
    | {
        label?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
        thought?: T;
        thoughtHighlight?: T;
        linkLabel?: T;
        linkHref?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noindex?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "creators-page_select".
 */
export interface CreatorsPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headingBlock?: T;
        headingHighlight?: T;
        subline?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  oneDegree?:
    | T
    | {
        heading?: T;
        body?: T;
        opportunities?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  whyGeek?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        headingHighlight?: T;
      };
  join?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subcopy?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noindex?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headingBlock?: T;
        headingHighlight?: T;
        formEyebrow?: T;
      };
  doors?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        items?:
          | T
          | {
              key?: T;
              title?: T;
              sub?: T;
              id?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noindex?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headingBlock?: T;
        headingHighlight?: T;
        subline?: T;
        ctaPrimaryLabel?: T;
        ctaPrimaryHref?: T;
        ctaSecondaryLabel?: T;
        ctaSecondaryHref?: T;
      };
  logoWall?:
    | T
    | {
        heading?: T;
        headingHighlight?: T;
      };
  build?:
    | T
    | {
        title?: T;
        sub?: T;
        trailing?: T;
      };
  create?:
    | T
    | {
        title?: T;
        sub?: T;
      };
  influence?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        sub?: T;
        list?: T;
        linkLabel?: T;
        linkHref?: T;
      };
  proof?:
    | T
    | {
        eyebrow?: T;
        sub?: T;
      };
  process?:
    | T
    | {
        heading?: T;
        headingHighlight?: T;
        trailing?: T;
      };
  builtByGeek?:
    | T
    | {
        eyebrow?: T;
        headingBlock?: T;
        headingCyan?: T;
        closing?: T;
        closingHighlight?: T;
      };
  geekWay?:
    | T
    | {
        title?: T;
        principles?:
          | T
          | {
              title?: T;
              body?: T;
              id?: T;
            };
        finaleBlock?: T;
        finaleHighlight?: T;
        finaleSub?: T;
      };
  work?:
    | T
    | {
        title?: T;
        sub?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noindex?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}